DROP TABLE IF EXISTS ap_status_history CASCADE;
DROP TABLE IF EXISTS ap_incidents CASCADE;
DROP TABLE IF EXISTS ap_checks CASCADE;
DROP TABLE IF EXISTS ap_applications CASCADE;
DROP TABLE IF EXISTS ap_users CASCADE;